#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cd /opt
rsync --exclude '.git' -a /source .
mv source foolscrate
cd foolscrate
make PYTHON="/usr/bin/python3" distclean devenv
ln -s /opt/foolscrate/devenv/bin/foolscrate /usr/bin/foolscrate

cd /out
# this is a standard fpm command. look at fpm's own help. The only thing that I like to do
# is installing all the things in a separate dir to prevent listing all the files - but it's
# just personal taste.
# remember to list all your runtime dependencies, e.g. the shared libraries you link to.
fpm -t deb -s dir -n foolscrate --version ${VERSION} --iteration "${BUILD_NUMBER}-jessie" --description "foolscrate ${GIT_COMMIT}" --depends python3 --depends git --depends cron -C / /opt/foolscrate /usr/bin/foolscrate
