#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cd /opt
rsync --exclude '.git' -a /source .
mv source foolscrate
cd foolscrate
make PYTHON="/usr/bin/python3" distclean devenv
ln -s /opt/foolscrate/devenv/bin/foolscrate /usr/bin/foolscrate

gpg --import /tmp/private.key
[[ $(gpg --list-secret-keys) =~ uid(.*) ]]
KEYNAME="${BASH_REMATCH[1]}"
[ -n "${KEYNAME}" ] || { echo "could not find key for signing purpose"; exit 1; }
echo -e "%_gpg_name ${KEYNAME}\n%_signature gpg\n" > ${HOME}/.rpmmacros

cd /out
# this is a standard fpm command. look at fpm's own help. The only thing that I like to do
# is installing all the things in a separate dir to prevent listing all the files - but it's
# just personal taste.
# remember to list all your runtime dependencies, e.g. the shared libraries you link to.
echo -e "\n" | setsid fpm -t rpm -s dir -n foolscrate --rpm-sign --version ${VERSION} --iteration "${BUILD_NUMBER}.centos7" --description "foolscrate ${GIT_COMMIT}" --depends python34 --depends git --depends cronie -C / /opt/foolscrate /usr/bin/foolscrate
