FROM alanfranz/fwd-fedora-24:latest
MAINTAINER Alan Franzoni <username@franzoni.eu>
# whatever is required for building should be installed in this image; just like BuildRequires: for RPM specs
RUN yum -y install rsync which findutils python3 python3-devel python3-virtualenv
