#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created logs will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /test-inside/test /test-logs/' EXIT

rpm --import /tmp/public.asc

yum -y localinstall /out/*.rpm

git config --global user.name "testing"
git config --global user.email "testing@example.com"

/opt/foolscrate/devenv/bin/unit discover -v -s /opt/foolscrate | tee /test-logs/foolscrate.log
