FROM alanfranz/fwd-ubuntu-trusty:latest
MAINTAINER Alan Franzoni <username@franzoni.eu>
# whatever is required for building should be installed in this image; just like BuildDeps for DEB projects.
RUN apt-get-current -y install python3 python3-dev rsync python-virtualenv
